{"name": "test002", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <scripts.test01.Test001 object at 0x00000228385E9A20>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test002(self):\n        print('\\n test001')\n>       assert False\nE       assert False\n\nscripts\\test01.py:14: AssertionError"}, "start": 1600136785393, "stop": 1600136785393, "uuid": "89bdc9d0-636d-4db9-85b5-5eb2a2c657cb", "historyId": "b0d4b5a07ff59f0d043bb21c00cab279", "testCaseId": "6753886712431c08107c02dbee94574f", "fullName": "scripts.test01.Test001#test002", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test01"}, {"name": "subSuite", "value": "Test001"}, {"name": "host", "value": "DESKTOP-3UT5IQU"}, {"name": "thread", "value": "10552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test01"}]}